function prediction = predict(this,unseen,varargin)

% predict  Predicts the class labels of a previously unseen data set.
%
% Syntax
%   prediction = predict(unseen);
%
% Description
%   prediction = predict(unseen) predicts class labels, generated by this
%   ChiMLModel, for each spectrum in unseen. unseen is a
%   ChiSpectralCollection and prediction is a ChiMLPrediction object. 
%   If unseen has a classmembership, then prediction will include a
%   property indicating whether the spectra were correctly classified.
% 
% Copyright (c) 2018-2019, Alex Henderson.
% Licenced under the GNU General Public License (GPL) version 3.
%
% See also 
%   ChiSpectralCollection ChiMLPrediction.

% Contact email: alex.henderson@manchester.ac.uk
% Licenced under the GNU General Public License (GPL) version 3
% http://www.gnu.org/copyleft/gpl.html
% Other licensing options are available, please contact Alex for details
% If you use this file in your work, please acknowledge the author(s) in
% your publications. 

% The latest version of this file is available on Bitbucket
% https://bitbucket.org/AlexHenderson/chitoolbox


%% Do we have the machine learning toolbox
if ~exist('fitcensemble','file')
    err = MException(['CHI:',mfilename,':InputError'], ...
        'The Statistics and Machine Learning Toolbox is required for this function.');
    throw(err);
end

%% Start timer
predictiontimer = tic();

%% Predict
if isa(this.model,'TreeBagger')
	[pred,scores,stdevs] = predict(this.model,unseen.data);
	pred = str2num(cell2mat(pred)); %#ok<ST2NM>
else	% fitcensemble
	[pred,scores] = predict(this.model,unseen.data);
	stdevs = zeros(size(scores));
end

%% Did we 'know' our 'unknowns'?
if ~isempty(unseen.classmembership)
    % Yes, our 'unknown' data already had class memberships. 
    % Let's see how many we got right. 
    correctlyclassified = (unseen.classmembership.labelids == pred);
else
    correctlyclassified = [];
end 

%% Stop timer
[predictiontime,predictionsec] = tock(predictiontimer);

%% Generate results
prediction = ChiMLPrediction(...
                pred, ...
                scores, ...
                stdevs, ...
                this.classmembership, ...
                predictiontime, ...
                predictionsec, ...
                correctlyclassified ...
            );

end
